feat(manager): add new source
ormushq/ormus pull request #46
Opened 2023-12-26 14:13 UTC by AmirAtashghah

2023-12-30 12:46 UTC, abtinokhovat requested changes
Great Job 👏
Please read my comments and give your opinion on it too.

2023-12-30 12:46 UTC, abtinokhovat commented on manager/param/source.go
I think you should separate structs and group them by request. For example:
- `addsource.go` or `add_source.go` or `source_add.go` : `AddSourceRequest`, `AddSourceResponse`

2023-12-30 12:46 UTC, abtinokhovat commented on manager/service/sourceservice/source.go
I have some problems with this:
1. Object initialization is dirty this way.
2. Also filling the data for `CreateAt`, `UpdateAt` are the responsibility of db queries and should be commented or removed from service layer.
3. Fields like `Status` which have default value (false) can be excluded, because they are initializing with nil value which in this case is `false`.

I suggested my ideal refactoring method, please comment if you have any suggestions so that we can reach the best situation.

```go
func (s *Service) CreateSource(req *param.AddSourceRequest) (*param.AddSourceResponse, error) {
	// now := time.Now()
	
	source := entity.Source{
		// WriteKey: "",  // TODO wait for our write key generator
		Name: req.Name,
		Description: req.Description,
		OwnerID: req.OwnerID,
		ProjectID: req.ProjectID,
		// Status: false, // it means source not active

		//CreateAt: now,
		//UpdatedAt: now,
	}

	if err := s.repo.InsertSource(source); err != nil {
		return nil, richerror.New("CreateSource").WhitWarpError(err)
	}

	response := param.AddSourceResponse{
		WriteKey: source.WriteKey,
		Name: source.Name,
		Description: source.Description,
		OwnerID: source.OwnerID,
		ProjectID: source.ProjectID,
		Status: source.Status,
		CreateAt: source.CreateAt,
		UpdateAt: source.UpdateAt,
	}

	return response, nil
}
```

2023-12-30 12:46 UTC, abtinokhovat commented on pkg/errmsg/message.go
This file should be removed, after #37 is merged, it will cause conflicts.

2023-12-30 12:46 UTC, abtinokhovat commented on pkg/richerror/richerror.go
Also this has to be removed (#37 ).

2023-12-30 12:46 UTC, abtinokhovat commented on manager/entity/source.go
WriteKey is better to be defined as a standalone type.

```go
type WriteKey string // because we might change the format in future

type Source struct {
	WriteKey    WriteKey
	// other fields
}
```

2023-12-30 12:46 UTC, abtinokhovat commented on manager/delivery/httpserver/sourcehandler/source.go
Each function should be separated in a standalone file.

- `sourcehandler/create.go`
- `sourcehandler/update.go`
- `sourcehandler/delete.go`

2023-12-30 12:46 UTC, abtinokhovat requested changes
Great Job 👏
Please read my comments and give your opinion on it too.

2023-12-30 13:05 UTC, abtinokhovat commented on manager/param/source.go
Also now I'm thinking about `writekey`, I now personally think that we should have a `source_id` because we may revoke `writekey`, we can update the `writekey` field in DB while revoking, but I think having a standalone id will be cleaner.

2023-12-30 13:10 UTC, abtinokhovat requested changes

2023-12-30 13:10 UTC, abtinokhovat commented on manager/service/sourceservice/source.go
Rename `AddSourceRequest` to `CreateSourceRequest`.

All methods have to be separated in their standalone single files.

- `sourceservice/create.go`
- `sourceservice/update.go`
- `sourceservice/delete.go`

2023-12-30 13:10 UTC, abtinokhovat commented on manager/validator/sourcevalidator/source.go
Also here like service separate methods, into standalone files.

2023-12-30 13:11 UTC, abtinokhovat requested changes
Fix Changes Please

2024-01-02 12:38 UTC, AmirAtashghah commented
I did everything that was said

2024-01-07 09:23 UTC, abtinokhovat approved these changes

2024-02-03 05:58 UTC, gocastsian commented on manager/delivery/httpserver/sourcehandler/delete.go
> +	sourceID := ctx.Param("sourceID")
Get UserID from context

2024-02-03 05:58 UTC, gocastsian commented on manager/service/sourceservice/delete.go
> +	return s.repo.DeleteSource(id)
Delete if record is owned by userID

2024-02-03 05:58 UTC, gocastsian commented on manager/delivery/httpserver/sourcehandler/route.go
> +	sourceGroups.POST("/create", h.CreateSource, middleware.GetTokenFromCookie(h.authSvc))
remove `/create`, `/remove`, `/update`
change `/source` to `/sources`

2024-02-17 04:53 UTC, merged